{
 "title": "锐捷 AC - WS6xxx 可视化管理面板",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AC状态总览",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "targets": [
    { "expr": "AC_RGOS_SysTime * 1000" },
    { "expr": "AC_Managed_APCount" },
    { "expr": "AC_Managed_OnlineUserCount" },
    {
     "expr": "AC_Managed_APTotalKbps{AC_IP=\"192.168.1.2\"} / 86400"
    },
    {
     "expr": "AC_Managed_APTotalDownKbps{AC_IP=\"192.168.1.2\"} / 86400"
    },
    {
     "expr": "AC_Managed_APTotalUpKbps{AC_IP=\"192.168.1.2\"} / 86400"
    },
    {
     "expr": "AC_Managed_User2GTotal{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "AC_Managed_User5GTotal{AC_IP=\"192.168.1.2\"}"
    }
   ]
  },
  {
   "title": "用户速率分布",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "User_Rate{AC_IP=\"192.168.1.2\"}"
    }
   ]
  },
  {
   "title": "受管 AP 趋势",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "AC_Managed_APCount{AC_IP=\"192.168.1.2\"}"
    }
   ]
  },
  {
   "title": "在线用户趋势",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "AC_Managed_OnlineUserCount{AC_IP=\"192.168.1.2\"}"
    }
   ]
  },
  {
   "title": "在线 AP 总览",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "AP_OnlineTime{AC_IP=\"192.168.1.2\"} / 86400"
    },
    {
     "expr": "AP_Downflow_kbps{AC_IP=\"192.168.1.2\"} / 8192"
    },
    {
     "expr": "AP_StaLimit{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "AP_Flow_kbps{AC_IP=\"192.168.1.2\"} / 8192"
    },
    {
     "expr": "AP_VtapStatus{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "AP_Cpu_percent{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "AP_OfflineCount{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "AP_Freememory_percent{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "AP_Upflow_kbps{AC_IP=\"192.168.1.2\"} / 8192"
    },
    {
     "expr": "AP_Stanum{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "AP_Ctxid{AC_IP=\"192.168.1.2\"}"
    }
   ]
  },
  {
   "title": "AC 在线用户总览",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "User_OnlineTimeval{AC_IP=\"192.168.1.2\"} / 60"
    },
    {
     "expr": "User_Rate{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "User_ApRadio{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "User_Delay{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "User_Ipv4downRate{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "User_Ipv4upRate{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "User_Ipv6downRate{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "User_Ipv6upRate{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "User_PacketLoss{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "User_Property80211{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "User_RSSI{AC_IP=\"192.168.1.2\"}"
    },
    {
     "expr": "User_VacId{AC_IP=\"192.168.1.2\"}"
    }
   ]
  }
 ]
}